In [34]:
import pandas as pd
import json

#baseDir='./data/hillsborough_200k/'
baseDir='./data/hills-1.45M/'

In [35]:
ward_to_zipcode=pd.read_csv('./wardNo_to_zipcode.csv')
ward_to_zipcode['wardIndex']=ward_to_zipcode['wardNo']-1
ward_to_zipcode

    wardNo  zipcode  wardIndex
0       44    33620         43
1        7    33548          6
2       11    33559         10
3        1    33503          0
4       28    33603         27
5       25    33596         24
6       40    33616         39
7        5    33534          4
8       22    33584         21
9        6    33547          5
10      35    33611         34
11      19    33573         18
12      34    33610         33
13      14    33566         13
14       2    33510          1
15       4    33527          3
16      36    33612         35
17      38    33614         37
18      42    33618         41
19      43    33619         42
20      50    33635         49
21      51    33637         50
22      52    33647         51
23       8    33549          7
24      13    33565         12
25      23    33592         22
26      24    33594         23
27      15    33567         14
28      16    33569         15
29      21    33579         20
30      17    33570         16
31      18    33572         17
32      27    33602         26
33      26    33598         25
34      30    33605         29
35      33    33609         32
36      49    33634         48
37      37    33613         36
38      45    33624         44
39      46    33625         45
40      48    33629         47
41      12    33563         11
42      39    33615         38
43      29    33604         28
44       3    33511          2
45      20    33578         19
46      41    33617         40
47       9    33556          8
48      10    33558          9
49      31    33606         30
50      32    33607         31
51      47    33626         46

In [36]:
df = pd.read_json(baseDir+'individuals.json')
#jarr = json.load(open(baseDir+'schools.json', 'r'))

In [37]:
df=pd.merge(df, ward_to_zipcode, on='wardIndex')

In [38]:
df
#jarr

,id,household,wardIndex,wardNo_x,lat,lon,CommunityCentreDistance,employed,workplaceType,age,workplace,school,wardNo_y,zipcode
0,0,0,0,1,27.760557,-82.271299,0.458825,1,1,42,17571.0,NaN,1,33503
1,1,0,0,1,27.760557,-82.271299,0.458825,1,1,53,14972.0,NaN,1,33503
2,2,1,0,1,27.765995,-82.271637,0.358152,1,1,43,14972.0,NaN,1,33503
3,3,1,0,1,27.765995,-82.271637,0.358152,1,1,38,18359.0,NaN,1,33503
4,4,1,0,1,27.765995,-82.271637,0.358152,1,1,18,14131.0,NaN,1,33503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459782,1459782,600650,51,52,28.147782,-82.317388,4.465406,1,1,15,46561.0,NaN,52,33647
1459783,1459783,600650,51,52,28.147782,-82.317388,4.465406,1,1,62,32058.0,NaN,52,33647
1459784,1459784,600650,51,52,28.147782,-82.317388,4.465406,1,1,42,34527.0,NaN,52,33647
1459785,1459785,600650,51,52,28.147782,-82.317388,4.465406,1,1,16,46433.0,NaN,52,33647
1459786,1459786,600650,51,52,28.147782,-82.317388,4.465406,1,1,42,31579.0,NaN,52,33647

In [49]:
df12=df[df['employed']!=1]
df12=df12[df12['zipcode']==33647]
df12

,id,household,wardIndex,wardNo_x,lat,lon,CommunityCentreDistance,employed,workplaceType,age,workplace,school,wardNo_y,zipcode
1388100,1388100,571256,51,52,28.163401,-82.374098,3.542425,0,2,3,NaN,514.0,52,33647
1388101,1388101,571256,51,52,28.163401,-82.374098,3.542425,0,0,44,NaN,NaN,52,33647
1388102,1388102,571256,51,52,28.163401,-82.374098,3.542425,0,0,0,NaN,NaN,52,33647
1388104,1388104,571258,51,52,28.133680,-82.291887,6.695368,0,0,1,NaN,NaN,52,33647
1388106,1388106,571258,51,52,28.133680,-82.291887,6.695368,0,2,5,NaN,505.0,52,33647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459772,1459772,600646,51,52,28.132993,-82.300398,5.861783,0,0,58,NaN,NaN,52,33647
1459773,1459773,600646,51,52,28.132993,-82.300398,5.861783,0,0,65,NaN,NaN,52,33647
1459777,1459777,600647,51,52,28.118966,-82.416163,5.740223,0,2,11,NaN,516.0,52,33647
1459779,1459779,600648,51,52,28.117943,-82.384633,2.991163,0,2,19,NaN,499.0,52,33647
1459780,1459780,600648,51,52,28.117943,-82.384633,2.991163,0,0,70,NaN,NaN,52,33647

In [40]:
df11 = pd.read_json(baseDir+'houses.json')
df11

            id  wardIndex  size        lat        lon
0            0          0     2  27.760557 -82.271299
1            1          0     6  27.765995 -82.271637
2            2          0     4  27.767628 -82.274431
3            3          0     3  27.759868 -82.264489
4            4          0     1  27.761429 -82.263134
...        ...        ...   ...        ...        ...
600646  600646         51     2  28.132993 -82.300398
600647  600647         51     5  28.118966 -82.416163
600648  600648         51     2  28.117943 -82.384633
600649  600649         51     1  28.090782 -82.362475
600650  600650         51     5  28.147782 -82.317388

[600651 rows x 5 columns]

In [41]:
df2 = pd.read_json(baseDir+'schools.json')
df2

      ID  wardIndex        lat        lon
0      0          0  27.770108 -82.274457
1      1          1  27.961498 -82.289229
2      2          1  27.941776 -82.299295
3      3          1  27.948944 -82.317575
4      4          1  27.941193 -82.316951
..   ...        ...        ...        ...
515  515         51  28.152120 -82.322637
516  516         51  28.138427 -82.329317
517  517         51  28.168878 -82.391102
518  518         51  28.121486 -82.381097
519  519         51  28.136245 -82.358813

[520 rows x 4 columns]

In [42]:
df3 = pd.read_json(baseDir+'workplaces.json')
df3

          id  wardIndex        lat        lon  officeType
0        520          0  27.766007 -82.280835           0
1        521          0  27.769057 -82.276873           3
2        522          0  27.762481 -82.268870           1
3        523          1  27.959125 -82.278478           3
4        524          1  27.959498 -82.303183           0
...      ...        ...        ...        ...         ...
47316  47836         51  28.131296 -82.362992           0
47317  47837         51  28.129580 -82.339837           0
47318  47838         51  28.151872 -82.326651           2
47319  47839         51  28.168483 -82.335616           0
47320  47840         51  28.157504 -82.343714           2

[47321 rows x 5 columns]

In [43]:
df4 = pd.read_json(baseDir+'commonArea.json')
df4

    ID  wardNo        lat        lon
0    0       1 -82.274250  27.763752
1    1       2 -82.299861  27.955636
2    2       3 -82.294053  27.909898
3    3       4 -82.213804  27.975712
4    4       5 -82.375052  27.822734
5    5       6 -82.136654  27.772392
6    6       7 -82.481835  28.137880
7    7       8 -82.446244  28.139197
8    8       9 -82.592642  28.170289
9    9      10 -82.515968  28.158712
10  10      11 -82.410065  28.157878
11  11      12 -82.125444  28.016939
12  12      13 -82.155953  28.088584
13  13      14 -82.117198  27.992406
14  14      15 -82.121698  27.921591
15  15      16 -82.290689  27.844291
16  16      17 -82.458614  27.693545
17  17      18 -82.399985  27.765903
18  18      19 -82.359995  27.721790
19  19      20 -82.347749  27.861866
20  20      21 -82.283760  27.795854
21  21      22 -82.289590  28.006373
22  22      23 -82.286980  28.100867
23  23      24 -82.242075  27.940807
24  24      25 -82.235911  27.887653
25  25      26 -82.290246  27.695309
26  26      27 -82.456746  27.953708
27  27      28 -82.464581  27.985262
28  28      29 -82.455193  28.016861
29  29      30 -82.429236  27.951212
30  30      31 -82.464926  27.932089
31  31      32 -82.514080  27.966767
32  32      33 -82.511076  27.943068
33  33      34 -82.380148  27.997202
34  34      35 -82.506321  27.890595
35  35      36 -82.450997  28.050705
36  36      37 -82.448727  28.083436
37  37      38 -82.505977  28.006193
38  38      39 -82.581440  28.005464
39  39      40 -82.528697  27.867123
40  40      41 -82.393271  28.038928
41  41      42 -82.497811  28.073129
42  42      43 -82.378415  27.935357
43  43      44 -82.411715  28.061121
44  44      45 -82.526078  28.079030
45  45      46 -82.560162  28.068068
46  46      47 -82.615261  28.062563
47  47      48 -82.510065  27.921809
48  48      49 -82.546138  28.007693
49  49      50 -82.618822  28.024079
50  50      51 -82.361181  28.047150
51  51      52 -82.360166  28.134006

In [44]:
df5 = pd.read_json(baseDir+'fractionPopulation.json')
df5

    wardNo  totalPopulation  fracPopulation
0        1              164        0.000112
1        2            29859        0.020454
2        3            59402        0.040692
3        4            15238        0.010439
4        5            17288        0.011843
5        6            26157        0.017918
6        7             7291        0.004995
7        8            18171        0.012448
8        9            23407        0.016035
9       10            24481        0.016770
10      11            18650        0.012776
11      12            28302        0.019388
12      13            18036        0.012355
13      14            21712        0.014873
14      15            12313        0.008435
15      16            28717        0.019672
16      17            30255        0.020726
17      18            20577        0.014096
18      19            23392        0.016024
19      20            52993        0.036302
20      21            36353        0.024903
21      22            27058        0.018536
22      23            11657        0.007985
23      24            35277        0.024166
24      25            31126        0.021322
25      26            20248        0.013871
26      27            15736        0.010780
27      28            21571        0.014777
28      29            39985        0.027391
29      30            17826        0.012211
30      31            20776        0.014232
31      32            24620        0.016865
32      33            18543        0.012703
33      34            47250        0.032368
34      35            33389        0.022873
35      36            52243        0.035788
36      37            36619        0.025085
37      38            49533        0.033932
38      39            47971        0.032862
39      40            16944        0.011607
40      41            47898        0.032812
41      42            27615        0.018917
42      43            40479        0.027729
43      44             5370        0.003679
44      45            40186        0.027529
45      46            27567        0.018884
46      47            31041        0.021264
47      48            27321        0.018716
48      49            22937        0.015713
49      50            18830        0.012899
50      51            17726        0.012143
51      52            71687        0.049108

In [51]:
df6 = pd.read_json(baseDir+'wardCentreDistance.json')
df6

,ID,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,52
0,1,0.000000,4.038558,3.099889,7.435854,11.242852,15.300465,23.732647,19.913774,35.900326,...,11.859547,15.907686,28.383183,32.103937,38.169365,26.324501,30.444097,38.503054,10.544323,11.025519
1,2,4.038558,0.000000,0.938993,9.573755,8.589943,18.356187,20.411746,16.500905,32.706636,...,8.739996,12.535140,25.219387,28.991016,35.105566,23.378988,27.395467,35.480931,6.952446,7.209277
2,3,3.099889,0.938993,0.000000,8.977622,9.098956,17.624039,21.148643,17.258037,33.419138,...,9.388175,13.273376,25.919284,29.680580,35.786089,24.020097,28.067259,36.151061,7.737378,8.069316
3,4,7.435854,9.573755,8.977622,0.000000,18.074386,9.114123,29.900196,25.959668,42.221807,...,18.313735,22.043322,34.756755,38.537251,44.658089,32.952360,36.956872,45.041496,16.422182,16.445259
4,5,11.242852,8.589943,9.098956,18.074386,0.000000,26.519315,12.739882,9.179543,24.717303,...,1.702861,5.378822,17.205661,20.891605,26.936072,15.082564,19.214356,27.263146,3.655412,4.885934
5,6,15.300465,18.356187,17.624039,9.114123,26.519315,0.000000,38.765554,34.856578,51.042891,...,26.993118,30.888286,43.540187,47.294788,53.390292,41.580639,45.665761,53.742806,25.303893,25.438127
6,7,23.732647,20.411746,21.148643,29.900196,12.739882,38.765554,0.000000,3.957639,12.330102,...,11.876271,7.877268,4.993142,8.767996,14.875945,4.438349,7.394756,15.320346,13.481921,13.529057
7,8,19.913774,16.500905,17.258037,25.959668,9.179543,34.856578,3.957639,0.000000,16.285029,...,8.114313,4.006140,8.920219,12.709136,18.826451,7.770143,11.270740,19.261808,9.554793,9.571649
8,9,35.900326,32.706636,33.419138,42.221807,24.717303,51.042891,12.330102,16.285029,0.000000,...,24.064698,20.180432,7.517338,3.898802,2.950098,9.856013,5.675065,3.584958,25.799668,25.855548
9,10,27.498871,24.214463,24.945183,33.707596,16.420798,42.565733,3.807410,7.758172,8.527465,...,15.639640,11.679381,1.610576,5.085543,11.127188,3.494631,4.002456,11.599662,17.288719,17.328091
10,11,16.191752,12.614111,13.411758,21.990815,6.284679,30.943132,7.985765,4.032122,20.302427,...,4.807398,1.432693,12.951123,16.741016,22.858411,11.640723,15.287716,23.293426,5.675242,5.559662
11,12,16.981816,19.416193,18.817737,9.845015,27.907401,3.925989,39.669724,35.717874,51.999464,...,28.155607,31.838735,44.557999,48.344356,54.469249,42.791273,46.779251,54.861194,26.216653,26.158964
12,13,14.034370,16.126177,15.589489,6.655290,24.685314,5.261727,36.243819,32.287625,48.572584,...,24.842599,28.442406,41.156283,44.947023,51.074101,39.453104,43.403129,51.477429,22.828743,22.717669
13,14,17.801322,20.318704,19.704703,10.745093,28.784769,3.988789,40.603632,36.653759,52.932371,...,29.058566,32.764945,45.483593,49.268113,55.391701,43.697453,47.696518,55.779980,27.142109,27.100360
14,15,17.129441,19.817383,19.165796,10.274492,28.210608,2.815509,40.174681,36.233646,52.495460,...,28.546313,32.315888,45.025713,48.803214,54.921040,43.184444,47.212842,55.298302,26.695862,26.707438
15,16,2.188091,1.948154,1.047488,8.773239,9.386175,17.162073,21.690041,17.836602,33.912412,...,9.847729,13.834811,26.400210,30.142975,36.231149,24.420154,28.505623,36.580980,8.397199,8.842628
16,17,20.526611,18.070699,18.574591,27.541265,9.483130,35.819584,6.970308,6.652663,16.421189,...,9.597478,7.493219,9.361625,12.528880,18.215313,6.614546,10.746691,18.442451,12.014519,12.715683
17,18,13.981158,11.482100,11.970523,20.936571,2.896074,29.281193,10.603688,7.510834,22.212594,...,3.461300,4.530057,14.745905,18.345576,24.320843,12.450214,16.628695,24.619594,5.984293,7.004408
18,19,9.554846,7.533646,7.846266,16.691515,2.241763,24.845964,14.858780,11.385243,26.680383,...,3.760172,7.620275,19.192159,22.823678,28.813157,16.941944,21.115039,29.113528,4.811289,6.093814
19,20,8.302028,5.504037,6.013170,14.990680,3.090579,23.510992,15.450279,11.687406,27.599188,...,3.578672,7.695666,20.082394,23.810416,29.888896,18.070141,22.162633,30.234150,3.121589,4.256446
20,21,1.161102,2.980643,2.050682,8.233059,10.159082,16.361164,22.594458,18.765841,34.780288,...,10.726808,14.760169,27.264039,30.992617,37.066543,25.232181,29.340355,37.406020,9.383409,9.870142
21,22,4.004592,1.369824,1.522035,8.439521,9.885769,17.367142,21.464280,17.529152,33.783031,...,9.932872,13.603851,26.317935,30.099829,36.222202,24.547254,28.526876,36.609824,7.983549,8.073378
22,23,5.230275,2.596384,2.955239,8.350308,10.627315,17.432718,21.673799,17.718390,34.003316,...,10.459429,13.882445,26.588495,30.380324,36.507469,24.945410,28.849552,36.916216,8.289308,8.152871
23,24,4.453483,6.429299,5.798184,3.187074,14.890397,11.995299,26.818693,22.891906,39.126394,...,15.160516,18.947515,31.645329,35.419128,41.534649,29.800494,33.824631,41.910094,13.338378,13.442832
24,25,4.649860,7.183254,6.473701,2.792350,15.501937,11.173500,27.594592,23.683089,39.882984,...,15.861616,19.717589,32.388223,36.152598,42.259549,30.488759,34.540955,42.624645,14.130708,14.295979
25,26,2.051367,4.025553,3.228201,9.482441,9.617662,17.117975,22.279145,18.543302,34.334909,...,10.430481,14.551490,26.822301,30.506487,36.535695,24.668720,28.820618,36.849903,9.461002,10.143396
26,27,20.485744,17.444901,18.102176,27.015878,9.285115,35.694986,3.871186,2.950426,15.432334,...,8.714214,5.248346,7.921508,11.618230,17.695981,5.946954,9.970778,18.050625,10.714635,11.060959
27,28,21.414987,18.321216,18.994302,27.885400,10.236581,36.601287,2.936418,3.034502,14.488939,...,9.609095,5.982237,6.972513,10.695711,16.791984,5.141131,9.074657,17.160014,11.533339,11.813929
28,29,20.464502,17.295795,17.987328,26.848173,9.355720,35.606798,3.447727,2.045554,15.443979,...,8.620745,4.877785,7.933649,11.695592,17.810905,6.256216,10.113504,18.194969,10.463155,10.705752
29,30,17.455495,14.386011,15.044014,23.957656,6.314125,32.642903,6.452511,3.338260,18.445268,...,5.655840,2.528655,10.927946,14.656939,20.747669,8.998047,13.024879,21.107355,7.697908,8.137656
30,31,21.347340,18.357671,19.002963,27.930903,10.121402,36.579498,3.538277,3.668474,14.613062,...,9.619684,6.210669,7.126836,10.771546,16.822260,5.021537,9.096770,17.163912,11.658890,12.020003
31,32,26.834740,23.820695,24.480162,33.389424,15.602001,42.066917,4.361985,7.949481,9.214922,...,15.092293,11.465357,2.102517,5.328844,11.334864,0.789765,3.613462,11.675889,17.042257,17.288547
32,33,26.465784,23.486793,24.136749,33.058615,15.227188,41.710825,4.309748,7.753641,9.642994,...,14.751673,11.181816,2.580260,5.749063,11.711760,0.327968,4.009178,12.037380,16.737019,17.011519
33,34,12.274797,8.948799,9.660441,18.499369,2.634939,27.283809,11.493254,7.639382,23.761900,...,0.932119,3.633912,16.270624,20.043257,26.160518,14.488119,18.457902,26.542177,2.234235,3.002672
34,35,25.872581,22.977201,23.604766,32.550653,14.630127,41.142479,4.507156,7.597805,10.411290,...,14.237535,10.809945,3.503465,6.513022,12.363973,0.614964,4.740404,12.656249,16.300736,16.637805
35,36,20.105579,16.863974,17.574597,26.398031,9.083703,35.198624,3.657003,1.396933,15.845077,...,8.246396,4.370550,8.358847,12.141273,18.266128,6.830704,10.597695,18.665292,9.987168,10.173773
36,37,19.967992,16.660243,17.388641,26.171061,9.042498,35.009399,3.766057,0.860448,16.051957,...,8.114932,4.128481,8.601306,12.393033,18.520148,7.214739,10.887331,18.933127,9.749260,9.875502
37,38,26.012997,22.931175,23.607390,32.491282,14.803513,41.213398,3.296280,6.918631,9.922928,...,14.222083,10.512071,2.471558,6.091061,12.178814,1.305153,4.465759,12.550389,16.111775,16.321088
38,39,34.341086,31.318729,31.986579,40.881619,23.102946,49.577750,11.239744,15.157532,2.672646,...,22.598461,18.889880,6.246611,2.531463,3.848543,8.027770,3.925544,4.165169,24.499258,24.675721
39,40,28.333987,25.478556,26.098729,35.051100,17.096823,43.615748,6.524824,9.985183,8.343177,...,16.740268,13.311343,3.078227,4.543955,10.027092,2.217819,2.807606,10.272196,18.811903,19.141612
40,41,13.849659,10.459709,11.196851,19.977946,3.775514,28.811821,9.953790,6.071148,22.251085,...,2.248854,2.076725,14.779111,18.562332,24.686527,13.099161,17.004201,25.081075,3.570270,3.939166
41,42,25.273185,22.078783,22.783739,31.612931,14.133544,40.406694,2.010295,5.814235,10.637538,...,13.428417,9.575001,3.144356,6.933539,13.060703,2.583644,5.456574,13.474348,15.197306,15.331330
42,43,11.859547,8.739996,9.388175,18.313735,1.702861,26.993118,11.876271,8.114313,24.064698,...,0.000000,4.139579,16.552964,20.301700,26.400721,14.640217,18.679830,26.763053,2.529145,3.566590
43,44,15.907686,12.535140,13.273376,22.043322,5.378822,30.888286,7.877268,4.006140,20.180432,...,4.139579,0.000000,12.719266,16.506857,22.633221,11.123292,14.967385,23.035463,5.622913,5.831692
44,45,28.383183,25.219387,25.919284,34.756755,17.205661,43.540187,4.993142,8.920219,7.517338,...,16.552964,12.719266,0.000000,3.793260,9.919449,2.890060,2.457085,10.342832,18.341657,18.466067
45,46,32.103937,28.991016,29.680580,38.537251,20.891605,47.294788,8.767996,12.709136,3.898802,...,20.301700,16.506857,3.793260,0.000000,6.127172,5.957757,1.785697,6.553104,22.127797,22.259318
46,47,38.169365,35.105566,35.786089,44.658089,26.936072,53.390292,14.875945,18.826451,2.950098,...,26.400721,22.633221,9.919449,6.127172,0.000000,11.871306,7.726310,0.677628,28.253244,28.384187
47,48,26.324501,23.378988,24.020097,32.952360,15.082564,41.580639,4.438349,7.770143,9.856013,...,14.640217,11.123292,2.890060,5.957757,11.871306,0.000000,4.198979,12.182387,16.656530,16.954963
48,49,30.444097,27.395467,28.067259,36.956872,19.214356,45.665761,7.394756,11.270740,5.675065,...,18.679830,14.967385,2.457085,1.785697,7.726310,4.198979,0.000000,8.085465,20.574386,20.761247
49,50,38.503054,35.480931,36.151061,45.041496,27.263146,53.742806,15.320346,19.261808,3.584958,...,26.763053,23.035463,10.342832,6.553104,0.677628,12.182387,8.085465,0.000000,28.650321,28.805517
50,51,10.544323,6.952446,7.737378,16.422182,3.655412,25.303893,13.481921,9.554793,25.799668,...,2.529145,5.622913,18.341657,22.127797,28.253244,16.656530,20.574386,28.650321,0.000000,1.288840
51,52,11.025519,7.209277,8.069316,16.445259,4.885934,25.438127,13.529057,9.571649,25.855548,...,3.566590,5.831692,18.466067,22.259318,28.384187,16.954963,20.761247,28.805517,1.288840,0.000000